/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arraylist;


import javax.swing.JOptionPane;

/**
 *
 * @author Internet
 */
public class ventanaInterfaz extends javax.swing.JFrame {
    
    public int listaNumeros [] = new int [100];
    public int indice = 0;
    

    /**
     * Creates new form ventanaInterfaz
     */
    public ventanaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numero = new javax.swing.JTextField();
        resultado = new javax.swing.JPanel();
        resultado2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        jPanel1.add(numero);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 100));

        resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resultado2.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout resultadoLayout = new javax.swing.GroupLayout(resultado);
        resultado.setLayout(resultadoLayout);
        resultadoLayout.setHorizontalGroup(
            resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        resultadoLayout.setVerticalGroup(
            resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultadoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 140));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        botonAgregar.setBackground(new java.awt.Color(102, 255, 102));
        botonAgregar.setText("Agregar");
        botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAgregarMouseExited(evt);
            }
        });
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(botonAgregar);

        botonMostrar.setBackground(new java.awt.Color(255, 204, 0));
        botonMostrar.setText("Mostrar");
        botonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMostrarMouseExited(evt);
            }
        });
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(botonMostrar);

        botonOrdenar.setBackground(new java.awt.Color(51, 255, 51));
        botonOrdenar.setText("Ordenar");
        botonOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonOrdenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonOrdenarMouseExited(evt);
            }
        });
        botonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarActionPerformed(evt);
            }
        });
        jPanel3.add(botonOrdenar);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
       // resultado2.setText (numero.getText());
       
       if (!validarNumeros(numero.getText().trim()))
       {
           JOptionPane.showMessageDialog(rootPane, "El dato es incorrecto");
           numero.setText("");
       }
       else 
        JOptionPane.showMessageDialog(rootPane, "El dato es correcto y a sido agregado");
       listaNumeros [indice]=Integer.parseInt(numero.getText());
       indice++;
       numero.setText("");
    }//GEN-LAST:event_botonAgregarActionPerformed
 
    
    public static boolean validarNumeros(String datos)
    {
        return datos.matches("[0-9]*");
    }
    
    
    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
        String mensaje = " ";
        for (int i=0; i< indice ;i ++)
        {
           mensaje = mensaje + listaNumeros [i]+"-";
           
        }
        resultado2.setText(mensaje);
        
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void botonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarActionPerformed
        // TODO add your handling code here:
        
        for(int i=0; i < (indice-1)  ;i ++)
          {
              for (int j=0;j<(indice-1);j++)
              {
                  if (listaNumeros[j]> listaNumeros [j+1])
                  {
                     int aux= listaNumeros[j];
                      listaNumeros[j]=listaNumeros[j+1];
                      listaNumeros[j+1]= aux;
                  }
              }
          }
        // Mostrar la lista ordenada 
        String mensajeLista = " ";
        for (int i=0;i<indice;i++)
        {
         mensajeLista = mensajeLista + listaNumeros [i]+"-";
        resultado2.setText(mensajeLista);
        }
    }//GEN-LAST:event_botonOrdenarActionPerformed

    // Cambiando color a los botones  
    
    private void botonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseEntered
        // TODO add your handling code here:
        botonAgregar.setBackground(new java.awt.Color(26, 188, 156));
        botonAgregar.setForeground(new java.awt.Color(0, 0, 0));
        
    }//GEN-LAST:event_botonAgregarMouseEntered

    private void botonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseExited
        // TODO add your handling code here:
         botonAgregar.setBackground(new java.awt.Color(46, 204, 113));
        botonAgregar.setForeground(new java.awt.Color(0, 0, 0));   
    }//GEN-LAST:event_botonAgregarMouseExited

    private void botonMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMostrarMouseEntered
        // TODO add your handling code here:
        
        botonMostrar.setBackground(new java.awt.Color(211, 84, 0));
        botonMostrar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_botonMostrarMouseEntered

    private void botonMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMostrarMouseExited
        // TODO add your handling code here:
        
        botonMostrar.setBackground(new java.awt.Color(155, 89, 182));
        botonMostrar.setForeground(new java.awt.Color(0, 0, 0));  
    }//GEN-LAST:event_botonMostrarMouseExited

    private void botonOrdenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOrdenarMouseEntered
        // TODO add your handling code here:
        botonOrdenar.setBackground(new java.awt.Color(231, 76, 60));
        botonOrdenar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_botonOrdenarMouseEntered

    private void botonOrdenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOrdenarMouseExited
        // TODO add your handling code here:
        botonOrdenar.setBackground(new java.awt.Color(231, 76, 60));
        botonOrdenar.setForeground(new java.awt.Color(0, 0, 0));
        
    }//GEN-LAST:event_botonOrdenarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new ventanaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonOrdenar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numero;
    private javax.swing.JPanel resultado;
    private javax.swing.JLabel resultado2;
    // End of variables declaration//GEN-END:variables
}
